examples/basic.rs, structopt-derive/src/lib.rs, tests/doc-comments-help.rs
This treats doc comments as `help`/`about` attributes, which may lead to concatenating the original help text with the doc comment.
I didn't add any tests except for changing the 'basic' example and checking the CLI output myself. If there is anything you want me to add in that regard, let me know :)
fix #13
=> Allow doc comment to set help text

Cargo.toml, README.md, examples/git.rs, src/lib.rs, structopt-derive/Cargo.toml, structopt-derive/src/lib.rs, tests/nested-subcommands.rs, tests/subcommands.rs
See #1 for detailed discussion of this feature.
Adds the ability to use `#[derive(StructOpt)]` on enums, thereby allowing the creation/easy parsing of `clap::SubCommand`s.
**This is not a breaking change.**
+ [X] Fix subcommand names that are hyphenated
+ [ ] Automatically downcase the names of subcommands for help messages (this could also apply to `#[derive(StructOpt)]` on structs or to changing argument names from `_` to `-`)
+ [x] Add the ability to use `about` attribute/doc comments on subcommand variants for help messages
+ [x] Allow other enum variant types than curly-bracketed ones (e.g. "blank" subcommands)
There are some commits that don't technically have anything to do with adding subcommands in:
+ Add documentation for the PR that added doc comments for help messages a few …
=> Add support for subcommands

structopt-derive/src/lib.rs
Cargo's `CARGO_PKG_AUTHORS` env var separates author names with a colon, which is not very pretty to look at. So, let's replace it with a comma. Clap has the same functionality it its `crate_authors!` macro but as it's only a few lines of code I didn't want to call that.
I wasn't sure how to add a test for that or if it's needed. I have a project locally where I `[replace]`d the structopt-derive crate with this branch and it works fine.
=> Format multiple authors

examples/raw_attributes.rs, structopt-derive/src/lib.rs, tests/raw_attributes.rs
This makes it possible to call clap functions that don't take strings,
but any arbitrary value. Even functions that take more than one argument
can be called.
All attributes that are called `attribute_name_raw` are augmented to
`attribute_name(value)` without quoting `value`.
This fixes #4.
For enums, I changed `AppSettings::SubcommandRequired` to `AppSettings::SubcommandRequiredElseHelp` if that's ok?
I find it much more useful if an application lists the help instead of telling me to get the help manually.
Unfortunately this behaviour of structopt cannot be overwritten by the user (no matter which one is used).
=> Add raw attributes

structopt-derive/src/lib.rs, tests/custom-string-parsers.rs
Fix #2.
Fix #3.
Syntax:
```rust
#[derive(StructOpt)]
struct HexReader {
#[structopt(short = "n", parse(try_from_str = "parse_hex"))]
number: u32,
#[structopt(short = "o", parse(from_os_str))]
output: PathBuf,
} 
```
* When using `structopt(parse(...))`, `bool` and `u64` will be treated as the same as `Ty::Other`, but `Vec<T>` and `Option<T>` remains special.
* The error in `try_from_str` will be converted to string using `.to_string()` instead of `.description()`, as the latter is not being recommended (see rust-lang/rust#44842 and rust-lang/rust#45249).
=> Implement custom string parser from either `&str` or `&OsStr`.

structopt-derive/src/lib.rs
Added a note about `clap::App`'s _raw methods, and an example specifically about colored help text.
=> Add doc on colored help

Cargo.toml, src/lib.rs
Clap comes with some colorful default features, which are not always useful or wanted, so allow opting out of them.
=> Allow opting out of clap default features.

examples/basic.rs, structopt-derive/src/lib.rs, tests/custom-string-parsers.rs, tests/flags.rs, tests/nested-subcommands.rs
Fixes #30. Can change to `from_occurrences` if you'd like.
=> Add 'parse(from_occurrences)' parser. Don't special case 'u64'.

README.md
`PathBuf` is in `std::path`, not `std::fs`.
=> Use proper path to 'PathBuf' in README

.travis.yml, CHANGELOG.md, Cargo.toml, structopt-derive/Cargo.toml, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/macros.rs
This avoids breakage when deriving `StructOpt` when `proc_macro2`'s nightly feature is enabled. See https://github.com/alexcrichton/proc-macro2/issues/67 for details.
cc @alexcrichton
=> Use `proc_macro2::Span::call_site` for all quotes

README.md
Hi!
While trying structopt, I noticed a mismatch in the README between the example code and the options in the resulting binary (`--car` vs. `--nb-cars`).
I believe it is due to an omission in 1383d64d102e1.
This PR aims at fixing the mismatch.
Thanks for this cool crate!
Thomas
=> Fix the `--nb-cars` option in the example

CHANGELOG.md, examples/flatten.rs, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/flatten.rs
=> Support flattening common options from a struct (#21)

CHANGELOG.md, src/lib.rs, tests/arguments.rs
I would like to be able to test argument parsing, which requires an error
value, not a `process::exit()`.
=> Add StructOpt::from_iter_safe method

Cargo.toml, structopt-derive/src/attrs.rs, tests/author_version_about.rs
Nice crate.
Fix code to transform a list of authors. It was doing no change, leaving colon separated list.
Style it as you like it.
I don't know how to test without also modifying the real authors list in Cargo.toml.
Ideas?
=> fix Cargo authors list insertion code

structopt-derive/src/lib.rs
This fixes a bug when a module is missing `use structopt::StructOpt`
which would result in the following error:
```
|
7 | #[derive(Debug, StructOpt)]
|                 ^^^^^^^^^ Use of undeclared type or module `StructOpt`
```
=> fully qualify StructOpt when flattening

.travis.yml, CHANGELOG.md, Cargo.toml, README.md, structopt-derive/Cargo.toml, structopt-derive/src/attrs.rs, tests/arguments.rs, tests/custom-string-parsers.rs
Fix #115
@zigguratvertigo @hcpl @killercup OK?
=> Add a minimum rustc version policy

structopt-derive/src/attrs.rs
=> Explicitly mention doc comments in flatten error

examples/simple_group.rs
This does change the behavior of the `group` example. The `vers` group is no longer required. It is is still a group, that is: only one of the several options are accepted.
I'm not sure this is an improvement to the example. It is much simpler and aligns with the ways I usually use groups, where they are not required.
=> Simplify `group` example

structopt-derive/Cargo.toml
This removes the dependency on syn 0.14 in downstream creates, which means you don't need to compile syn 0.14 and 0.15. Surprisingly, this update worked by just increasing the version number.
=> Upgrade syn to 0.15

examples/doc_comments.rs, examples/enum_in_args.rs, examples/raw_attributes.rs, src/lib.rs, structopt-derive/src/attrs.rs, tests/doc-comments-help.rs
First approach of an implementation of the smarter doc comment parsing feature requested in #134.
It introduces an additional check in the doc comment parsing algorithm to test if the second line of a given doc comment is an empty line. If this is true only the first line will be used as input for the argument given as input parameter (`help` or `about`) at the same time it applies the whole comment as input for the related long version (`long_help` and `long_about`).
This patch *doesn't* contain the additional feature I requested in [this comment](https://github.com/TeXitoi/structopt/issues/134#issuecomment-429464231). It would be easy to add it but I assume as long as it isn't clearly defined how to switch between the two behaviors it should not be introduced.
=> Introduce smarter parsing of doc comments.

structopt-derive/src/attrs.rs
There was a typo preventing the probematic attr to be shown to the user.
=> Fix invalid structopt syntax error message

README.md, examples/basic.rs, structopt-derive/src/lib.rs
was found in comments and code, but required no user-facing API change.
Tests were execute successfully.
The misspelled comments lead me to a 
```
#[structopt(short = "v", long = "verbose", parse(from_occurences))]
```
which fails with a
```
error: proc-macro derive panicked                                                                                                           
--> src/main.rs:17:10                                                                                                                     
|                                                                                                                                        
17 | #[derive(StructOpt, Debug)] …
```
=> Fix spelling: occurences -> occurrences,

src/lib.rs
During reading doc, found some typos.
=> Typo fix on lib.rs

structopt-derive/src/attrs.rs, tests/doc-comments-help.rs
This makes the generated short help more natural for the command-line,
while allowing the rustdoc text to have the period that's standard for
rustdoc comments.
=> Remove line-ending periods from short help.

.travis.yml, examples/enum_in_args.rs, structopt-derive/src/lib.rs
Fixes #177. We cannot change `.map_err(|e| e.to_string())` to `.map_err(ToString::to_string)` since `e` is not a reference in most cases. Instead, we have to wirte
- `.map_err(|e| (&e).to_string())`
or
- `.map_err(|e| ::std::string::ToString::to_string(&e))`
to suppress the warning.
The upstream clippy has already stopped triggering the warning for macros. This hack will be obsolete, but the current stable clippy will keep producing the warning until Rust 1.35 is released.
rust-lang/rust-clippy/pull/3816
=> Suppress `clippy::redundant_closure`

CHANGELOG.md, examples/example.rs, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/options.rs
Closes #188 
I used `sub_type` function in `Attrs` module, so I moved it to there and exported so that it can be reused in `lib.rs`, I am not sure this is an optimal solution, please let me know if you want to change that (for example to have a separate module for types manipulations or anything else).
Another thing that I wanted to add to tests: is to make sure that `Option<Option<T>>` cannot be used for positional arguments. In this case I would expect a macro code-generation to fail, but I'm not sure how to make a test which expects particular macro failure. For now, I just checked that it works manually.
Also please note that I am using `max_values=1` as well as `min_values=0` to limit number of values to 1 in the generated `clap` code. However, handling of `max_option` in `clap` …
=> Support Option<Option<T>> field types

CHANGELOG.md, examples/example.rs, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/options.rs
Closes #180 
The code is quite similar to adding support of `Option<Option<T>>`
=> Support Option<Vec<T>> field type

CHANGELOG.md, Cargo.toml, src/lib.rs, structopt-derive/Cargo.toml, structopt-derive/src/lib.rs
Create an optional feature that when turned on add in the required paw:ParseArgs trait implementation that allows use of StructOpt as the argument for the fn main.
=> Optionally add paw support for structopt as a feature

structopt-derive/Cargo.toml, structopt-derive/src/attrs.rs
Update deprecated `interpret_meta` function from `syn`, as mentioned in https://github.com/TeXitoi/structopt/issues/178#issuecomment-497946337
=> Update deprecated function and provide more info about the parsing error

src/lib.rs
For some reason, the possibility of using numbers and booleans in attribute values has not been mentioned in the documentation. Perhaps, it was not supported before or doesn't work with some older Rust versions. 
I've added it to the documentation, but please let me know if there any hidden issues here.
=> Docs: tell about possible literals use for attribute values

CHANGELOG.md, examples/rename_all.rs, src/lib.rs, structopt-derive/src/lib.rs, tests/argument_naming.rs, tests/deny-warnings.rs, tests/subcommands.rs
.. fixes TeXitoi/structopt#202
I hope I discovered all related comments and text snippets.
=> [Casing] Change default from verbatim to kebab.

CHANGELOG.md, examples/example.rs, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, tests/skip.rs, tests/ui/skip_flatten.rs, tests/ui/skip_flatten.stderr, tests/ui/skip_subcommand.rs, tests/ui/skip_subcommand.stderr, tests/ui/skip_with_other_options.rs, tests/ui/skip_with_other_options.stderr, tests/ui/skip_without_default.rs, tests/ui/skip_without_default.stderr
=> Support skipping struct fields

structopt-derive/src/lib.rs
The name `Result` is evaluated in the user context, which may break when another `Result` type is used. For example, in the presence of [the basic error-chain quickstart](https://github.com/rust-lang-nursery/error-chain/blob/master/examples/quickstart.rs), this leads to:
```
Compiling application v0.0.1 (/home/ghast/rust-cli-template)
error[E0107]: wrong number of type arguments: expected 1, found 2
--> src/main.rs:13:10
|
13 | #[derive(structopt::StructOpt, Debug)]
|          ^^^^^^^^^^^^^^^^^^^^ unexpected type argument
error: aborting due to previous error
For more information about this error, try `rustc --explain E0107`.
error: Could not compile `application`.
```
By explicitly specifying the `Result` type, this name clash can be resolved correctly.
=> Explicitly specify the Result type

CHANGELOG.md, examples/no_version.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, structopt-derive/src/spanned.rs, tests/author_version_about.rs, tests/doc-comments-help.rs, tests/raw_bool_literal.rs, tests/ui/raw.rs, tests/ui/raw.stderr
=> Change `author/about/version` behavior

CHANGELOG.md, examples/skip.rs, src/lib.rs
Closes #214 
@TeXitoi There are a couple of TODOs in changelog, I could use some advise there
=> Update and improve documentation

CHANGELOG.md, structopt-derive/src/parse.rs
=> Fix error messages

structopt-derive/src/lib.rs
Closes #262 
Now we put `#[allow(clippy)]` on top of every `impl` block, suppressing **all** clippy warnings, not just select few. In my opinion, any attempt to generate "flawless" code is meaningful and useless.
=> Suppress all clippy warnings

structopt-derive/src/lib.rs
Even after #263 I'm still getting some warnings.
```
warning: called `map(f).unwrap_or_else(g)` on an Option value. This can be done more directly by calling `map_or_else(g, f)` instead
--> src\main.rs:167:15
|
167 |         urls: Vec<String>,
|               ^^^
|
= note: replace `map(Vec).unwrap_or_else(Vec)` with `map_or_else(Vec, Vec)`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#option_map_unwrap_or_else
```
I think this one is probably just worth fixing?
Tests all pass still, of course, since this doesn't change any behavior at all.
=> Fix clippy warnings

CHANGELOG.md, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/flags.rs
Fixes #185 
This PR adds the `from_flag` parser type which allows non bool field types to be treated as flags.
=> Add from_flag parser

src/lib.rs
`structopt`'s documentation has grown much, now it's not easy to navigate. Table of contents would help a lot.
=> Add table of contents in documentation

src/lib.rs
Fixes #107 
Simply adds an observation to the docs stating that the `StructOpt` trait is more than `from_args`.
Please feel free to point any mistakes. Especially in my English, since it isn't my first language.
=> docs: observes that the trait is more than from_args

src/lib.rs
Optional subcommands do not have to be nested
=> Fix documentation inaccuracy

structopt-derive/src/attrs.rs
Old implementation will forbid parse for Option<Vec<T>> and the error message is not helpful.
=> Fix parse for OptionVec ref pull #191

CHANGELOG.md, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/spanned.rs, tests/explicit_name_no_renaming.rs, tests/macro-errors.rs, tests/raw_idents.rs, tests/ui/non_existent_attr.stderr, tests/ui/skip_with_other_options.stderr, tests/ui/subcommand_and_methods.stderr
Closes #269 #265 
Single PR because this changes are on top of one another
=> Fix #269 and #265

CHANGELOG.md, structopt-derive/src/lib.rs, tests/custom-string-parsers.rs
In most cases this doesn't matter, as &String is coerced to a &str, but
this fails for generic functions like CString::new.
The added test failed to compile before this change.
=> Pass the try_from_str functions a &str instead of a &String.

examples/negative_flag.rs
Question from https://github.com/TeXitoi/structopt/issues/280
=> Add an example of a negative flag (i.e. --no-verbose)

structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/ty.rs, tests/special_types.rs
While thinking on #285 I suggested to use `::vec::Vec` instead of `Vec` to prevent special casing, but a simple test proved me wrong. In fact, **any path that ends with `Vec<T>` will be considered as `Vec<T>`** which is wrong. The same goes for `Option` and `bool`.
I believe this is a bug and it should be fixed. This PR handles paths correctly, checking not only the last segment but also verifying that the said segment is *the only one* segment present, no leading `::`.
Technically, this is a breaking change but I believe this is a bug and, furthermore, I really doubt someone out there has been relying on this behavior.
=> Handle special types correctly

CHANGELOG.md, structopt-derive/src/lib.rs, tests/issues.rs
Fixes #151 
Fixes #289 
Fixes #113
=> Handle inter-expansion top-level args properly

examples/README.md, examples/true_or_false.rs, src/lib.rs, structopt-derive/src/attrs.rs, tests/ui/positional_bool.rs, tests/ui/positional_bool.stderr
Closes #212
cc @TeXitoi please also take a look at #292
=> Prohibit positional bool

examples/group.rs
Fixed typo, removed misleading doc. I removed the doc because it was either that or implement some logic, and I thought removing it was nicer.
=> Minor fix on group example

src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, tests/rename_all_env.rs
=> Introduce #[structopt(rename_all_env)]

Cargo.toml, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/doc_comments.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, structopt-derive/src/spanned.rs, tests/doc-comments-help.rs
First commit ensures explicit handling of doc commits and sets strict priority among raw methods and doc comments, see `stc/lib.rs` diff for details. Closes #173 
Second commit introduces `no_mangle_docs` attributes. Fixes #163 
cc @TeXitoi @0ndorio @ssokolow
=> Consistent doc comments

src/lib.rs, structopt-derive/src/lib.rs
Closes #304 
This PR makes `is_subcommand`, `from_subcommand`, and `augment_clap` part of the `StructOpt` trait (marking them as `doc(hidden)`. I believe this is justifiable change because:
* The change is 100% backward compatible.
* These methods won't ever collide with user's methods. 
* This way we could add more `impl`s in future with ease.
* The change is fairly small and straightforward.
=> impl StructOpt for Box<impl StructOpt>

CHANGELOG.md, Cargo.toml, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/parse.rs, tests/default_value.rs
This is not meant to be released with the next patch, just some ongoing work.
Closes #123 
Closes #142
Closes #150 
TODO: docs, changelog
=> Default value

.travis.yml
Currently, every PR send by me triggers two identical CI builds: a build for push and a build for PR.
This way we trigger a build only for PRs and pushes to master.
Just stumbled upon it while was surfing across some project :)
=> CI: build only PRs and pushes to master

Cargo.toml, structopt-derive/Cargo.toml
We don't really need the "full" feature for syn, we don't even need some of the default features.
I also opted-in to "diff" for trybuild, quite useful feature.
=> Get rid of syn-full

.gitignore, CHANGELOG.md, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, structopt-derive/src/ty.rs, tests/subcommands.rs, tests/ui/external_subcommand_wrong_type.rs, tests/ui/external_subcommand_wrong_type.stderr, tests/ui/multiple_external_subcommand.rs, tests/ui/multiple_external_subcommand.stderr
Closes #130 
I took some time to develop and debug, but it's finally ready. I have one concern thought.
=> Introduce `#[structopt(external_subcommand)]`

src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/spanned.rs, tests/flatten.rs, tests/ui/enum_flatten.rs, tests/ui/enum_flatten.stderr, tests/ui/struct_flatten.stderr
Resolving merge conflicts in #329 
@cecton, your authorship is preserved, sorry again for the mess.
=> Flatten for enums

.travis.yml, CHANGELOG.md, src/lib.rs, structopt-derive/src/lib.rs
The correctness category is for code that's outright wrong. I think we should not generate such code and the extra check won't hurt.
=> Suppress all clippy lints except correctness

examples/README.md, examples/required_if.rs, src/lib.rs
The `required_if` example in `lib.rs` doesn't actually require `file_name` when `out_type=file` because the arg name is wrong: clap uses hyphens for word separators, not underscores. This change fixes the example to use `out-type`. I decided against adding an inline test to keep the crate docs succinct.
I also added a separate `required_if` example with tests to validate this behavior. I separated this change into a separate commit in case you just want the typo fix without the new example.
Thank you for structopt!
=> Fix typo in required_if usage in crate docs

examples/rename_all.rs, src/lib.rs, structopt-derive/src/attrs.rs, tests/argument_naming.rs
Some programs do not use anything to separate word boundaries.
For example a struct may contain the field `build_dir` while the flag is
`--builddir`.
=> Add support for lower/upper in rename_all

structopt-derive/src/lib.rs
=> Fix wrong span

README.md, src/lib.rs, structopt-derive/src/lib.rs
Closes #432 
@TeXitoi Do you mind if I do a new patch release with this change? Just so `cargo geiger` would list structopt as green.
=> Forbid unsafe

CHANGELOG.md, src/lib.rs, structopt-derive/src/lib.rs, tests/generics.rs
This PR provides (at least basic) support for generics when deriving `StructOpt` (issue #128). It's probably not the ideal final implementation, but from what I can see, it improves the situation and makes some use cases possible.
=> add basic support for generic structs and enums

Cargo.toml
This requires no code changes, the example still compiles fine.
strum 0.21 claims to have an MSRV of 1.32.0, and structopt's MSRV is 1.36.0, so that should not be a problem either.
=> Bump strum dev-dependency to latest version (0.20 -> 0.21)

CHANGELOG.md, structopt-derive/src/lib.rs, tests/issues.rs
This PR closes #490. Please refer to #490 for the detail of the problem.
Let me know if you want to make `convert_type` a function.
=> Fix the problem where the build fails due to the ambiguous type of `map`

CHANGELOG.md, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/subcommands.rs
=> Add skip attribute support for enum variants

src/lib.rs, tests/ui/skip_without_default.stderr
* some formatting improvements in code blocks
* get rid of most `ignored` and the `should_panic`
* especially the `should_panic` was confusing IMO, because rustdoc renders it with a huge red bar, (like a deliberately failing example) even though it’s supposed to demonstrate a working app (scaffolding)
=> Improve code blocks in documentation

src/lib.rs
When I first started using structopt, I had also not used clap. It wasn't clear to me that clap contained a ton of functionality, and that the clap docs were the likely place to look if I needed to change some default behavior. The structopt docs are perfectly clear as is, but I think adding links will drive home the point that there are a ton of extra methods available (listed in the clap documentation).
Additionally, linking to the list of clap methods may be convenient for users browsing the structopt documentation who realize something they need doesn't exist in structopt.
=> Link to the clap method list in the documentation

examples/README.md, examples/after_help.rs, examples/at_least_two.rs, examples/basic.rs, examples/deny_missing_docs.rs, examples/doc_comments.rs, examples/enum_in_args.rs, examples/enum_in_args_with_strum.rs, examples/enum_tuple.rs, examples/env.rs, examples/example.rs, examples/flatten.rs, examples/gen_completions.rs, examples/git.rs, examples/group.rs, examples/keyvalue.rs, examples/negative_flag.rs, examples/no_version.rs, examples/rename_all.rs, examples/required_if.rs, examples/subcommand_aliases.rs
When viewing examples, it is very hard to figure out what they do without running them, which requires substantial efforts.  I have added the output of all examples at the top.
Also, two tiny spelling mistakes - in the readme and in the rename_all.
In case anyone wants to auto-generate something similar, I used this helper script, and made a few minor line manipulations afterwards.
```bash
run() {
RES=$(cargo run -q --example "$1" -- --help 2> /dev/null | sed -e 's#^#//! #' )
{ echo "//! Running this example with --help prints this message:" ; echo "//! -----------------------------------------------------" ; echo "$RES" ; echo "//! -----------------------------------------------------" ; echo "" ; cat "examples/$1.rs" ; } > "$1.rs"
rm "examples/$1.rs"
mv "$1.rs" "examples/"
}
run …
```
=> [docs] Add output to all examples

README.md
clap-rs/clap#3422 drew attention to the lack of discoverability of the
migration guide.  We've added it to the clap FAQ item about structopt.
Adding it here as well in hopes people will find it.
=> docs: Link to clap3 migration guide

README.md
This just fixes a link in README.md 😄
=> Fix link to the migration guide
