TeXitoi/structopt

CHANGELOG.md
A follow up to a comment by @ErichDonGubler here: https://github.com/TeXitoi/structopt/issues/188#issuecomment-497362982
=> Improve ChangeLog as suggested by @ErichDonGubler

examples/env.rs
=> Add example for environment variables

examples/keyvalue.rs
=> Update keyvalue example

CHANGELOG.md
=> Fix changelog example

CHANGELOG.md, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs
It looks like we can arguing on #243 just forever. 
Docs are upcoming
fixes #243
=> Do not call .verison() when CARGO_PKG_VERSION is not set

src/lib.rs
=> Update version in the documentation

CHANGELOG.md, examples/skip.rs, src/lib.rs, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, tests/skip.rs
=> Support `skip = value` syntax

src/lib.rs
=> Fix version in docs (AGAIN)

structopt-derive/src/attrs.rs
Fix code formatting error reported [here](https://travis-ci.org/TeXitoi/structopt/jobs/592644921).
This is an addition to #266 fix, trying to help mitigate CI errors.
=> Fix code formatting

src/lib.rs, structopt-derive/src/parse.rs, tests/ui/raw.stderr
Docs are never clear enough, perfection is a moving goal but it doesn't
mean we should stop :)
=> Clarify docs and error messages

structopt-derive/Cargo.toml, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, structopt-derive/src/parse.rs, tests/ui/parse_empty_try_from_os.stderr, tests/ui/raw.stderr, tests/ui/struct_parse.stderr
cc @TeXitoi please double check error messages
=> Update proc-macro-error to v0.4

examples/README.md, examples/after_help.rs
=> Add `after_help` example

link-check-headers.json
=> Send headers to all web sites

tests/author_version_about.rs, tests/doc-comments-help.rs, tests/explicit_name_no_renaming.rs, tests/subcommands.rs, tests/utils.rs
A separate PR because my other work-in-progress depends on utils,rs
=> Add tests/utils.rs

.travis.yml, CHANGELOG.md, src/lib.rs, structopt-derive/src/parse.rs, tests/issues.rs, tests/ui/raw.rs, tests/ui/raw.stderr
@TeXitoi merge this and you can go and release a new patch
=> Pre release tweaks and changelog

CHANGELOG.md, structopt-derive/src/attrs.rs, structopt-derive/src/lib.rs, tests/author_version_about.rs
=> Propagate no version

structopt-derive/src/lib.rs
=> Silence all clippy warnings in generated code

src/lib.rs
Forgot to push before merge :( Where are my memory pills?
=> Tidy up some doctests

structopt-derive/src/attrs.rs, tests/doc-comments-help.rs
Signed-off-by: David McNeil <mcneil.david2@gmail.com>
=> Fix verbatim_doc_comment on fields

CHANGELOG.md, Cargo.toml, structopt-derive/Cargo.toml
=> Enable syn(clone-impls) feature

src/lib.rs
You can't even imagine how tired I am from being asked this question again and again 😢
=> Put some extra emphasis on raw methods

structopt-derive/src/lib.rs, tests/issues.rs, tests/ui/non_existent_attr.stderr
Closes #359 
Rejoice, @scrogson, the fix has arrived!
=> Make external_subcommand work even with one arg

structopt-derive/Cargo.toml
=> Upgrade to proc-macro-error 1.0.0

Cargo.toml, tests/macro-errors.rs, tests/ui/tuple_struct.stderr
=> Fix license in Cargo.toml

src/lib.rs
fixes #389
Couldn't find a way to test this properly.
=> Fix first doc example for a practical one

structopt-derive/src/lib.rs, structopt-derive/src/spanned.rs
=> Remove unnecessary braces

structopt-derive/src/lib.rs, tests/flatten.rs
=> Flattening a subcommand now panics with a meaningful error message

Cargo.toml, src/lib.rs, structopt-derive/src/lib.rs
=> Reexport paw

CHANGELOG.md, Cargo.toml, structopt-derive/Cargo.toml
I should have done it 10 days ago but forgot. I'm sorry.
=> Point release
